version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "automated"
    reviewers: []
    # Optionally, ignore rules can be added here.

