package fr.univtln.bruno.samples.java101.tp1.lombok;

import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;


/**
 * Tests for the Lombok-powered {@link PersonLombok} class. Shows that Lombok's
 * builder, getters and setters behave as expected (builder creates instance,
 * setters mutate it, getters reflect the mutation).
 */
class PersonLombokTest {

    /**
     * Verify builder, getters and setters generated by Lombok.
     */
    @Test
    void lombokBuilderAndAccessors() {
        PersonLombok p = PersonLombok.builder().firstName("L").lastName("M").age(40).build();
        assertThat(p.getFirstName()).isEqualTo("L");
        p.setFirstName("N");
        assertThat(p.getFirstName()).isEqualTo("N");
    }
}
